version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.3
    container_name: artifactory
    ports:
     - 80:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
