version: '2'
services:
  elasticsearch1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    container_name: re-dock_elasticsearch1
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
       - data1:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=re-ops
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node

  elasticsearch2:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    container_name: re-dock_elasticsearch2
    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
       - data2:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=re-ops
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node


volumes:
    data1:
      driver: local
    data2:
      driver: local

