version: '2.3'
services:
  postgres:
    image: postgres:9.6.4
    restart: always
    volumes:
     - ./postgresdata:/var/lib/postgresql/data
     - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "synapse_user" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
     - POSTGRES_USER=synapse_user
    networks: ['matrix']
     
  element:
    image: vectorim/element-web:latest
    restart: always
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8080:80"
        
  synapse:
    image: matrixdotorg/synapse:latest
    restart: "unless-stopped"
    depends_on: ['postgres']
    ports:
     - "8008:8008"
    volumes:
     - ./matrix/synapse:/data
    networks: ['matrix']

networks: {matrix: {}}
