version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./logs:/var/log/nginx/log
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
      - ./htpasswd/:/etc/htpasswd
    ports:
      - 443:443
    network_mode: host
